// <auto-generated />
using System;
using Lottery.Web.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace Lottery.Web.Migrations
{
    [DbContext(typeof(DataContext))]
    partial class DataContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.1.8-servicing-32085")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("Lottery.Web.Data.Entities.Banca", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<bool>("IsAvailabe");

                    b.Property<int?>("LoteriaId");

                    b.Property<double>("Monto");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(60);

                    b.Property<int?>("ZonaId");

                    b.HasKey("Id");

                    b.HasIndex("LoteriaId");

                    b.HasIndex("ZonaId");

                    b.ToTable("Bancas");
                });

            modelBuilder.Entity("Lottery.Web.Data.Entities.Dia", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<bool>("IsAvailabe");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(60);

                    b.HasKey("Id");

                    b.ToTable("Dias");
                });

            modelBuilder.Entity("Lottery.Web.Data.Entities.Frecuencia", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<bool>("IsAvailabe");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(60);

                    b.HasKey("Id");

                    b.ToTable("Frecuencias");
                });

            modelBuilder.Entity("Lottery.Web.Data.Entities.Gasto", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<bool>("IsAvailabe");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(60);

                    b.HasKey("Id");

                    b.ToTable("Gastos");
                });

            modelBuilder.Entity("Lottery.Web.Data.Entities.GastoDetalle", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("DiaId");

                    b.Property<int?>("FrecuenciaId");

                    b.Property<int>("GastoId");

                    b.Property<bool>("IsAvailabe");

                    b.Property<double>("Monto");

                    b.HasKey("Id");

                    b.HasIndex("DiaId");

                    b.HasIndex("FrecuenciaId");

                    b.HasIndex("GastoId");

                    b.ToTable("GastoDetalles");
                });

            modelBuilder.Entity("Lottery.Web.Data.Entities.Horario", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("HorarioFinaliza")
                        .HasMaxLength(15);

                    b.Property<string>("HorarioInicio")
                        .HasMaxLength(15);

                    b.Property<bool>("IsAvailabe");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(60);

                    b.HasKey("Id");

                    b.ToTable("Horarios");
                });

            modelBuilder.Entity("Lottery.Web.Data.Entities.Localidad", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<bool>("IsAvailabe");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(60);

                    b.Property<int>("Zona");

                    b.HasKey("Id");

                    b.ToTable("Localidads");
                });

            modelBuilder.Entity("Lottery.Web.Data.Entities.Loteria", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Horario")
                        .HasMaxLength(15);

                    b.Property<bool>("IsAvailabe");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(60);

                    b.Property<string>("Sigla")
                        .HasMaxLength(5);

                    b.HasKey("Id");

                    b.ToTable("Loterias");
                });

            modelBuilder.Entity("Lottery.Web.Data.Entities.Precio", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<double>("Cash3Box");

                    b.Property<double>("Cash3Straight");

                    b.Property<double>("Directo");

                    b.Property<int>("IdLoteria");

                    b.Property<bool>("IsAvailabe");

                    b.Property<double>("Pale");

                    b.Property<double>("Pick2");

                    b.Property<double>("Pick5Box");

                    b.Property<double>("Pick5String");

                    b.Property<double>("Play4Box");

                    b.Property<double>("Play4Straight");

                    b.Property<double>("SuperPale");

                    b.Property<double>("Tripleta");

                    b.HasKey("Id");

                    b.ToTable("Precios");
                });

            modelBuilder.Entity("Lottery.Web.Data.Entities.Propietario", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<bool>("IsAvailabe");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(60);

                    b.HasKey("Id");

                    b.ToTable("Propietarios");
                });

            modelBuilder.Entity("Lottery.Web.Data.Entities.Zona", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<bool>("IsAvailabe");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(60);

                    b.Property<string>("Sigla")
                        .HasMaxLength(5);

                    b.HasKey("Id");

                    b.ToTable("Zonas");
                });

            modelBuilder.Entity("Lottery.Web.Data.Entities.Banca", b =>
                {
                    b.HasOne("Lottery.Web.Data.Entities.Loteria", "Loteria")
                        .WithMany()
                        .HasForeignKey("LoteriaId");

                    b.HasOne("Lottery.Web.Data.Entities.Zona", "Zona")
                        .WithMany()
                        .HasForeignKey("ZonaId");
                });

            modelBuilder.Entity("Lottery.Web.Data.Entities.GastoDetalle", b =>
                {
                    b.HasOne("Lottery.Web.Data.Entities.Dia", "Dia")
                        .WithMany()
                        .HasForeignKey("DiaId")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.HasOne("Lottery.Web.Data.Entities.Frecuencia", "Frecuencia")
                        .WithMany()
                        .HasForeignKey("FrecuenciaId");

                    b.HasOne("Lottery.Web.Data.Entities.Gasto", "Gasto")
                        .WithMany()
                        .HasForeignKey("GastoId")
                        .OnDelete(DeleteBehavior.Cascade);
                });
#pragma warning restore 612, 618
        }
    }
}
